server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: bookmanager
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
